name: actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list of files
        run: |
          pwd
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: checkout code from git 
        uses: actions/checkout@v1
      - name: list of files after checkout
        run: |
          pwd
          ls -a 
      - name: sample js actions
        id: greeting1
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Bhaskar
      - name: log Greeting time
        run: echo "${{steps.greeting1.outputs.time}}"
